exagon:
  kafka:
    consumers:
      internal:
        bootstrap-server: ${KAFKA_BOOTSTRAP_SERVERS}
        auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET}
        group-id: mock-kafka
        session-timeoutMS: ${KAFKA_SESSION_TIMEOUT_MS}
    producers:
      internal:
        bootstrap-server: ${KAFKA_BOOTSTRAP_SERVERS}

logging:
  level:
    org.apache: INFO
    com.alticelabs.ccp: DEBUG